The test scripts updated to what Trond copied from SME during the weekend, with one small change by Sandra. The code is Ciprian's, Lene's and Trond's improvements of the original lemma generation test scripts (and some regressions or questionable decisions that I will return to soon).

diff --git a/test/src/morphology/generate-adjective-lemmas.sh.in b/test/src/morphology/generate-adjective-lemmas.sh.in
--- a/test/src/morphology/generate-adjective-lemmas.sh.in
+++ b/test/src/morphology/generate-adjective-lemmas.sh.in
@@ -1,18 +1,47 @@
 #!/bin/bash
+# @configure_input@
 
-# Dette skriptet tester at nesten alle lemmaene i
-# $GTHOME/langs/sma/src/morphology/stems/adjectives.lexc kan genereres.
-# De som ikke kan genereres, kopieres til missingAdjLemmas.txt
+# Automake interprets the exit status as follows:
+# - an exit status of 0 will denote a success
+# - an exit status of 77 a skipped test
+# - an exit status of 99 a hard error
+# - any other exit status will denote a failure.
+
+# To run this test script only, do:
+#
+# make check TESTS=generate-adj-lemmas.sh
+
+# This test script will test that all adj lemmas do generate as themselves.
+# Adj lemmas that do not generate properly are output in langs/$lang/test/data/missing_adj_lemma.txt
+# Extend as needed, and copy to new files to adapt to other parts of speech.
+# The changes usually needed are:
+#
+# 1. change the reference to the source file (line 23)
+# 2. extend the extract lemmas egrep expression (lines 53 ff)
+# 3. adapt the tag addition and lemma generation instructions (lines 79 ff)
 
 ###### Variables: #######
-sourcefile=${srcdir}/../../../src/morphology/stems/adjectives.lexc
-generatorfile=./../../../src/generator-gt-norm
-resultfile=missingAdjLemmas
+### in ###
+source_file=${srcdir}/../../../src/morphology/stems/adjectives.lexc
+generator_file=./../../../src/generator-gt-norm
 
-# Check that the source file exists:
-if [ ! -f "$sourcefile" ]; then
-	echo Source file not found: $sourcefile
-	exit 1
+### out ###
+lemmas=./filtered-adjs.tmp
+lemmas_pl=./filtered-pl_adjs.tmp
+lemmas_attr=./filtered-attr_adjs.tmp
+lemmas_super=./filtered-super_adjs.tmp
+lemmas_comp=./filtered-comp_adjs.tmp
+all_adjs=./all_adjs.tmp
+generated_lemmas=./generated-adjs.tmp
+result_file=${srcdir}/../../data/missing_adj_lemmas
+
+
+# FAIL if source file does not exist:
+if [ ! -f $source_file ]; then
+    echo
+    echo "*** Warning: Source file $source_file not found."
+    echo
+    exit 77
 fi
 
 # Use autotools mechanisms to only run the configured fst types in the tests:
@@ -21,7 +50,7 @@ fsttype=
 @CAN_XFST_TRUE@fsttype="$fsttype xfst"
 
 # Exit if both hfst and xerox have been shut off:
-if [ -z $fsttype ]; then
+if test -z "$fsttype" ; then
     echo "All transducer types have been shut off at configure time."
     echo "Nothing to test. Skipping."
     exit 77
@@ -30,36 +59,45 @@ fi
 # Get external Mac editor for viewing failed results from configure:
 EXTEDITOR=@SEE@
 
-###### Extraction: #######
-### Regular adjectives:
-grep ";" $sourcefile | grep -v "^\!" \
-	| egrep -v "(LEXATTR|OANEP|NUORTTALABBO|GASSKALAMOS|TJAVGGÁMUS)" \
-	| egrep -v "( At |PrfPrc_At|VINJO|DEMONSTRATIJVA)" \
-	| tr ":+\t" " " | cut -d " " -f1 \
-	| tr -d "#" | grep -v '^$' | grep -v 'LEXICON' | sort -u > adjs.txt
-### Adjectives with no pred form, ie only attr form:
-grep ";" $sourcefile | grep -v "^\!" \
-	| egrep "( At |PrfPrc_At|LEXATTR|DEMONSTRATIJVA)" \
-	| tr ":+\t" " " | cut -d " " -f1 \
-	| tr -d "#" | grep -v '^$' | grep -v 'LEXICON' | sort -u > attradjs.txt
-### Adjectives with only comparative forms:
-grep ";" $sourcefile | grep -v "^\!" \
-	| egrep "(OANEP|NUORTTALABBO)" | tr ":+\t" " " \
-	| cut -d " " -f1 | tr -d "#" \
-	| grep -v '^$' | sort -u > compadjs.txt
-### Adjectives with only superlative forms:
-grep ";" $sourcefile | grep -v "^\!" \
-	| egrep "(GASSKALAMOS|TJAVGGÁMUS)" | tr ":+\t" " " | cut -d " " -f1 \
-	| grep -v '^$' | tr -d "#" | sort -u > superladjs.txt
-### Adjectives with only superlative forms:
-grep ";" $sourcefile | grep -v "^\!" \
-	| grep "VINJO" | tr ":+\t" " " | cut -d " " -f1 \
-	| grep -v '^$' | sort -u > compoundadjs.txt
+##### Extract lemmas #####
+### don't use extract-lemmas.sh ###
+
+# Hent ut lemmaer, bortsett fra utkommmenterte (^\!):
+
+# 1. dem med hardkoding for spesielle former (K), LexSub (som blir filtrert bort fra normgenerator), adjektiver som bare har attributtform (ATTR|Attr| At ) , adjektiver som krever tagger for komparering (BBO |MUS |BUOREMUSS|OVDDIT |STUORIBUS|BUStem) og lemmaer som bare opptrer i sammensetninger (FINJU|Rreal | R) Lemmaene lagres som $lemmas
+grep ";" $source_file | grep -v "^\!" |\
+   egrep -v "(LEXICON|ATTR|FINJU|Der|Attr| At |BBO |MUS |BUOREMUSS|OVDDIT |STUORIBUS|BUStem | K | Rreal | R |LexSub)" |\
+   sed 's/% /€/g' | sed 's/%:/¢/g' |  tr ":+" " " | cut -d " " -f1 | tr -d "%" | tr "€" " " | tr "¢" ":" |\
+   sort -u > $lemmas
+
+# 2. for plurale lemmaer (_PL). Lemmaene lagres som $lemmas_pl
+grep ";" $source_file | grep -v "^\!" |\
+  grep -v "+Gen" | grep -v LexSub | grep "_PL " | tr ":+" " " |\
+  cut -d " " -f1 | tr -d "%" | sort -u > $lemmas_pl
+
+# 3. som bare har attributtform. Lagres i $lemmas_attr
+grep ";" $source_file | grep -v "^\!" |\
+  grep -v "+Gen" | grep -v LexSub | egrep "(ATTR|Attr)" |\
+  sed 's/% /€/g' | sed 's/%:/¢/g' |  tr ":+" " " | cut -d " " -f1 |\
+  tr -d "%" | tr "€" " " | tr "¢" ":" | sort -u > $lemmas_attr
+
+# 4. som krever superlativtagg. Lagres i $lemmas_super
+grep ";" $source_file | grep -v "^\!" |\
+  grep "BUOREMUSS" | grep -v LexSub | tr ":+" " " |\
+  cut -d " " -f1 | tr -d "%" | sort -u > $lemmas_super
+
+# 5. som krever komparativtagg. Lagres i $lemmas_comp
+grep ";" $source_file | grep -v "^\!" |\
+  egrep "(OVDDIT|BBO |BU/MUS|EABBO/EAMOS|STUORIBUS|BUStem)" |\
+  grep -v LexSub | tr ":+" " " | cut -d " " -f1 | tr -d "%" |\
+  sort -u > $lemmas_comp
+
 
 ###### Start testing: #######
 transducer_found=0
 Fail=0
 
+# The script tests both Xerox and Hfst transducers if available:
 for f in $fsttype; do
 	if [ $f == "xfst" ]; then
 		lookuptool="@LOOKUP@ -q -flags mbTT"
@@ -69,51 +107,63 @@ for f in $fsttype; do
 		suffix="hfstol"
 	else
 	    Fail=1
-		echo "Unknown fst type!"
+		printf "ERROR: Unknown fst type! "
 	    echo "$f - FAIL"
 	    continue
 	fi
-	if [ -f "$generatorfile.$suffix" ]; then
+	if [ -f "$generator_file.$suffix" ]; then
 		let "transducer_found += 1"
 
-#### First we try to generate the regular adjectives:
-		sed 's/$/+A+Sg+Nom/' adjs.txt | $lookuptool $generatorfile.$suffix \
-			| cut -f2 | grep -v "A+" | grep -v "^$" | sort -u > analadjs.$f.txt
+###### Test generation: #######
+		# generate adjectives, extract the resulting generated lemma,
+		# store it:
 
-#### Then we try to generate the attribute-only adjectives:
-		sed 's/$/+A+Attr/' attradjs.txt \
-			| $lookuptool $generatorfile.$suffix | cut -f2 \
-			| grep -v "A+" | grep -v "^$" | sort -u >> analadjs.$f.txt
+# Generer former:
 
-#### Then we try to generate the comparative-only adjectives:
-		sed 's/$/+A+Comp+Sg+Nom/' compadjs.txt \
-			| $lookuptool $generatorfile.$suffix | cut -f2 \
-			| grep -v "A+" | grep -v "^$" | sort -u >> analadjs.$f.txt
+# 1. med +A+Sg+Nom (grunnformen for de fleste). Lagres som $generated_lemmas.$f.txt
+		sed 's/$/+A+Sg+Nom/' $lemmas | $lookuptool $generator_file.$suffix \
+            | cut -f2 | grep -v "A+" | grep -v "^$" | sort -u > $generated_lemmas.$f.txt
 
-#### Then we try to generate the superlative-only adjectives:
-		sed 's/$/+A+Superl+Sg+Nom/' superladjs.txt \
-			| $lookuptool $generatorfile.$suffix | cut -f2 \
-			| grep -v "A+" | grep -v "^$" | sort -u >> analadjs.$f.txt
+# 2. med +A+Pl+Nom for plurale lemmaer. Lagres i $generated_lemmas.$f.txt
+		sed 's/$/+A+Pl+Nom/' $lemmas_pl | $lookuptool $generator_file.$suffix \
+            | cut -f2 | grep -v "A+" | grep -v "^$" | sort -u >> $generated_lemmas.$f.txt
 
-#### Then we try to generate the compound-only adjectives:
-		sed 's/CmpN\/SgN$/A+Attr+Cmp#bijlla+N+Sg+Nom/' compoundadjs.txt \
-			| sed 's/CmpN\/PlG$/A+Attr+Cmp#bijlla+N+Sg+Nom/' \
-			| sed 's/$/+A+Attr+Cmp#bijlla+N+Sg+Nom/' \
-			| $lookuptool $generatorfile.$suffix | cut -f2 | sed 's/bijlla$//' \
-			| grep -v '^$' | tr 'ä' 'æ' >> analadjs.$f.txt
+# 3. med +A+Attr lemmaer som bare har attributtform. Lagres i $generated_lemmas.$f.txt
+		sed 's/$/+A+Attr/' $lemmas_attr | $lookuptool $generator_file.$suffix \
+            | cut -f2 | grep -v "A+" | grep -v "^$" | sort -u >> $generated_lemmas.$f.txt
 
-		cat predadjs.txt superladjs.txt compladjs.txt >> adjs.txt
-		sort -u -o adjs.txt adjs.txt
-		sort -u -o analadjs.$f.txt analadjs.$f.txt
-		comm -23 adjs.txt analadjs.$f.txt > $resultfile.$f.txt
+# 4. for lemmaer lemmaer som krever superlativtagg, med +A+Superl+Sg+Nom. Lagres i $generated_lemmas.$f.txt
+		sed 's/$/+A+Superl+Sg+Nom/' $lemmas_super | $lookuptool $generator_file.$suffix \
+            | cut -f2 | grep -v "A+" | grep -v "^$" | sort -u >> $generated_lemmas.$f.txt
 
-		# if at least one word is found, the test failed, and the list of failed
-		# lemmas is opened in SubEthaEdit:
-		if [ -s $resultfile.$f.txt ]
-		then
+# 5. for lemmaer lemmaer som krever komparativtagg, med +A+Comp+Sg+Nom. Lagres i $generated_lemmas.$f.txt
+		sed 's/$/+A+Comp+Sg+Nom/' $lemmas_comp | $lookuptool $generator_file.$suffix \
+            | cut -f2 | grep -v "A+" | grep -v "^$" | sort -u >> $generated_lemmas.$f.txt
+
+###### Collect results: #######
+		# Sort and compare original input with resulting output - the diff is
+		# stored and opened in SEE:
+
+# Samle alle lemmaer i en fil, sorter, unifiser
+cat $lemmas $lemmas_pl $lemmas_attr $lemmas_super $lemmas_comp > $all_adjs
+sort -u -o $all_adjs $all_adjs 
+
+# Alle genererte former sorteres og unifiseres.
+sort -u -o $generated_lemmas.$f.txt $generated_lemmas.$f.txt 
+		
+# Sammenlikne lista med verblemmaer med den genererte lista med infinitivsformer.
+# Formene som er i verblemmalista, men ikke i den genererte lista, kopieres til
+# missingverbLemmas.txt. Formene generes med  +V+Inf for lettere debugging.
+
+		comm -23 $lemmas $generated_lemmas.$f.txt \
+		     | grep -v '^$' | sed 's/$/+A+Sg+Nom/' \
+		     | $lookuptool $generator_file.$suffix > $result_file.$f.txt
+
+		# Open the diff file in SubEthaEdit (if there is a diff):
+		if [ -s $result_file.$f.txt ]; then
 			# Only open the failed lemmas in see if @SEE@ is defined:
 			if [ "$EXTEDITOR" ]; then
-				$EXTEDITOR $resultfile.$f.txt
+				$EXTEDITOR $result_file.$f.txt
 			fi
 		    Fail=1
 		    echo "$f - FAIL"
@@ -123,8 +173,8 @@ for f in $fsttype; do
 	fi
 done
 
-# Delete temporary files:
-rm -f *adjs.txt
+# When done, remove the generated data file:
+rm -f $lemmas $lemmas_pl $lemmas_attr $lemmas_super $lemmas_comp $all_adjs $generated_lemmas.$f.txt
 
 # At least one of the Xerox or HFST tests failed:
 if [ "$Fail" = "1" ]; then
@@ -132,6 +182,6 @@ if [ "$Fail" = "1" ]; then
 fi
 
 if [ $transducer_found -eq 0 ]; then
-    echo No transducer found
-    exit 1
+    echo ERROR: No transducer found
+    exit 77
 fi
diff --git a/test/src/morphology/generate-noun-lemmas.sh.in b/test/src/morphology/generate-noun-lemmas.sh.in
--- a/test/src/morphology/generate-noun-lemmas.sh.in
+++ b/test/src/morphology/generate-noun-lemmas.sh.in
@@ -1,17 +1,40 @@
 #!/bin/bash
+# @configure_input@
 
-# Dette skriptet tester at alle lemmaene i noun-sma-lex.txt kan genereres.
-# De som ikke kan genereres, kopieres til missingNounLemmas.txt
+# Automake interprets the exit status as follows:
+# - an exit status of 0 will denote a success
+# - an exit status of 77 a skipped test
+# - an exit status of 99 a hard error
+# - any other exit status will denote a failure.
+
+# To run this test script only, do:
+#
+# make check TESTS=generate-noun-lemmas.sh
+
+# This test script will test that all noun lemmas do generate as themselves.
+# Extend as needed, and copy to new files to adapt to other parts of speech.
+# The changes usually needed are:
+#
+# 1. change the reference to the source file (line 23)
+# 2. extend the extract lemmas egrep expression (lines 53 ff)
+# 3. adapt the tag addition and lemma generation instructions (lines 79 ff)
 
 ###### Variables: #######
-sourcefile=${srcdir}/../../../src/morphology/stems/nouns.lexc
-generatorfile=./../../../src/generator-gt-norm
-resultfile=missingNounLemmas
+### in ###
+source_file=${srcdir}/../../../src/morphology/stems/nouns.lexc
+generator_file=./../../../src/generator-gt-norm
 
-# Check that the source file exists:
-if [ ! -f "$sourcefile" ]; then
-	echo Source file not found: $sourcefile
-	exit 1
+### out ###
+lemmas=./filtered-nouns
+generated_lemmas=./generated-nouns
+result_file=${srcdir}/missing_noun_lemmas.txt
+
+# FAIL if source file does not exist:
+if [ ! -f $sourcefile ]; then
+    echo
+    echo "*** Warning: Source file $sourcefile not found."
+    echo
+    exit 77
 fi
 
 # Use autotools mechanisms to only run the configured fst types in the tests:
@@ -20,7 +43,7 @@ fsttype=
 @CAN_XFST_TRUE@fsttype="$fsttype xfst"
 
 # Exit if both hfst and xerox have been shut off:
-if [ -z $fsttype ]; then
+if test -z "$fsttype" ; then
     echo "All transducer types have been shut off at configure time."
     echo "Nothing to test. Skipping."
     exit 77
@@ -29,28 +52,28 @@ fi
 # Get external Mac editor for viewing failed results from configure:
 EXTEDITOR=@SEE@
 
-###### Extraction: #######
-# extract non-compounding lemmas:
-grep ";" $sourcefile | grep -v "^\!" \
-	| egrep -v "(CmpN/Only|\+Gen\+|\+Der\+| R | RHyph|CmpN/Pref)" \
-	| sed 's/% /€/g' \
-	| sed 's/%:/¢/g' | tr ":+\t" " " | cut -d " " -f1 | tr -d "#" \
-	| tr "€" " " | tr "¢" ":" \
-	| sort -u | grep -v '^$' > nouns.txt
+##### Extract lemmas #####
+### don't use extract-lemmas.sh ###
+# Hent ut lemmaer fra den nouns.lexc, bortsett fra utkommmenterte (^\!), 
+# dem som krever sammensetning (CmpN/Only|ShCmp|RCmpnd| Rreal | R | Rnoun),
+# LexSub (som blir filtrert bort fra normgenerator). Lemmaene lagres som filtered-nouns
 
-# extract compounding lemmas:
-grep ";" $sourcefile | grep -v "^\!" \
-	| grep ' R '| tr ":+\t" " " | cut -d " " -f1 | tr -d "#" \
-	| sort -u > Rnouns.txt
-# extract compounding lemmas requiring hyphen:
-grep ";" $sourcefile | grep -v "^\!" \
-	| grep ' RHyph '| tr ":+\t" " " | cut -d " " -f1 | tr -d "#" \
-	| sort -u > RHnouns.txt
+grep ";" $source_file | \
+  egrep -v "^(\!|\@|<)" | \
+  egrep -v '(CmpN/Only|ShCmp|RCmpnd| Rreal | R | Rnoun |\+V\+|\+Err\/)' | \
+  sed 's/% /€/g' | sed 's/%:/¢/g' |  tr ":+" " " | cut -d " " -f1 | \
+  tr -d "%" | tr "€" " " | tr "¢" ":" | sort -u > $lemmas
+
+# evt. denne, sjekk skilnaden:
+# @GTCORE@/scripts/extract-lemmas.sh \
+# 	$sourcefile "(CmpN/Last)" > $lemmas
+
 
 ###### Start testing: #######
 transducer_found=0
 Fail=0
 
+# The script tests both Xerox and Hfst transducers if available:
 for f in $fsttype; do
 	if [ $f == "xfst" ]; then
 		lookuptool="@LOOKUP@ -q -flags mbTT"
@@ -60,50 +83,48 @@ for f in $fsttype; do
 		suffix="hfstol"
 	else
 	    Fail=1
-		echo "Unknown fst type!"
+		printf "ERROR: Unknown fst type! "
 	    echo "$f - FAIL"
 	    continue
 	fi
-	if [ -f "$generatorfile.$suffix" ]; then
+	echo "$generator_file.$suffix"
+	if [ -f "$generator_file.$suffix" ]; then
 		let "transducer_found += 1"
 
 ###### Test non-comopunds: #######
 		# generate nouns in Singular, extract the resulting generated lemma,
 		# store it:
-		sed 's/$/+N+Sg+Nom/' nouns.txt | $lookuptool $generatorfile.$suffix \
-			| cut -f2 | grep -v "N+" | grep -v "^$" | sort -u > analnouns.$f.txt
-		# Generate nouns, extract those that do not generate in singular,
-		# generate the rest in plural:
-		sed 's/$/+N+Sg+Nom/' nouns.txt | $lookuptool $generatorfile.$suffix \
-			| cut -f2 | grep "N+" | cut -d "+" -f1 | sed 's/$/+N+Pl+Nom/' \
-			| $lookuptool $generatorfile.$suffix | cut -f2 \
-			| grep -v "^$" >> analnouns.$f.txt
+# Generer lemmaer i nouns med +N+Sg+Nom, lagre i generated-nouns
+sed 's/$/+N+Sg+Nom/' $lemmas | $lookuptool $generator_file.$suffix | \
+  cut -f2 | grep -v "N+" | grep -v "^$" | sort -u > $generated_lemmas.$f.txt		
+		
+# Generer plurale lemmaer i filtered-nouns med +N+Pl+Nom (som ikke lar seg generer med +N+Sg+Nom).
+# Lagre dem i generated-nouns
+sed 's/$/+N+Sg+Nom/' $lemmas | $lookuptool $generator_file.$suffix | \
+  cut -f2 | grep "N+" | cut -d "+" -f1 | sed 's/$/+N+Pl+Nom/' | \
+  $lookuptool $generator_file.$suffix | \
+  cut -f2 | grep -v "^$" >> $generated_lemmas.$f.txt 
 
-###### Test comopunds: #######
-		# Test nouns that only can generate as compounds:
-		sed 's/$/+N+Cmp#bijlla+N+Sg+Nom/' Rnouns.txt \
-			| $lookuptool $generatorfile.$suffix | cut -f2 | sed 's/bijlla$//' \
-			| grep -v '^$' >> Ranalnouns.$f.txt
-		sed 's/$/+N+Cmp-#bijlla+N+Sg+Nom/' RHnouns.txt \
-			| $lookuptool $generatorfile.$suffix | cut -f2 | sed 's/\-bijlla$//' \
-			| grep -v '^$' >> RHanalnouns.$f.txt
 
 ###### Collect results: #######
 		# Sort and compare original input with resulting output - the diff is
 		# stored and opened in SEE:
-		sort -u -o analnouns.$f.txt analnouns.$f.txt
-		sort -u -o Ranalnouns.$f.txt Ranalnouns.$f.txt
-		sort -u -o RHanalnouns.$f.txt RHanalnouns.$f.txt
-		comm -23 nouns.txt analnouns.$f.txt > $resultfile.$f.txt
-		comm -23 Rnouns.txt Ranalnouns.$f.txt >> $resultfile.$f.txt
-		comm -23 RHnouns.txt RHanalnouns.$f.txt >> $resultfile.$f.txt
 
-		# if at least one word is found, the test failed, and the list of failed
-		# lemmas is opened in SubEthaEdit:
-		if [ -s $resultfile.$f.txt ]; then
+# Sorter, unifiser
+sort -u -o $lemmas $lemmas 
+sort -u -o $generated_lemmas.$f.txt $generated_lemmas.$f.txt 
+
+# Sammenlikne: Former som er i lemmalista med ikke i lista med genererte former,
+# lagre i missingnounLemmas.txt. Formene generes med  +N+Sg+Nom for enklere debugging.
+comm -23 $lemmas $generated_lemmas.$f.txt |\
+  grep -v '^$' | sed 's/$/+N+Sg+Nom/' |\
+  $lookuptool $generator_file.$suffix > $result_file.$f.txt
+
+		# Open the diff file in SubEthaEdit (if there is a diff):
+		if [ -s $result_file.$f.txt ]; then
 			# Only open the failed lemmas in see if @SEE@ is defined:
 			if [ "$EXTEDITOR" ]; then
-				$EXTEDITOR $resultfile.$f.txt
+				$EXTEDITOR $result_file.$f.txt
 			fi
 		    Fail=1
 		    echo "$f - FAIL"
@@ -113,8 +134,8 @@ for f in $fsttype; do
 	fi
 done
 
-# Delete temporary files:
-rm -f *nouns.*.txt
+# When done, remove the generated data file:
+rm -f $lemmas
 
 # At least one of the Xerox or HFST tests failed:
 if [ "$Fail" = "1" ]; then
@@ -122,6 +143,6 @@ if [ "$Fail" = "1" ]; then
 fi
 
 if [ $transducer_found -eq 0 ]; then
-    echo No transducer found
-    exit 1
+    echo ERROR: No transducer found
+    exit 77
 fi
