[Template merge - langs/und] Modernised the generate-noun-lemmas.sh.in script, added similar scripts for adj, proper nouns and verbs.

diff --git a/test/src/morphology/generate-noun-lemmas.sh.in b/test/src/morphology/generate-noun-lemmas.sh.in
--- a/test/src/morphology/generate-noun-lemmas.sh.in
+++ b/test/src/morphology/generate-noun-lemmas.sh.in
@@ -20,19 +20,23 @@
 # 3. adapt the tag addition and lemma generation instructions (lines 89 ff)
 
 ###### Variables: #######
+POS=nouns
 ### in ###
-source_file=${srcdir}/../../../src/morphology/stems/nouns.lexc
+source_file=${srcdir}/../../../src/morphology/stems/${POS}.lexc
 generator_file=./../../../src/generator-gt-norm
+analyser_file=./../../../src/analyser-gt-norm
 
 ### out ###
-lemmas=./filtered-nouns
-generated_lemmas=./generated-nouns
-result_file=missing_noun_lemmas
+lemmas=./filtered-${POS}
+generated_lemmas=./generated-${POS}
+result_file=missing_${POS}_lemmas
+gen_result_file=generated_missing_${POS}_lemmas
+ana_result_file=analysed_missing_${POS}_lemmas
 
-# FAIL if source file does not exist:
-if [ ! -f $sourcefile ]; then
+# SKIP if source file does not exist:
+if [ ! -f $source_file ]; then
     echo
-    echo "*** Warning: Source file $sourcefile not found."
+    echo "*** Warning: Source file $source_file not found."
     echo
     exit 77
 fi
@@ -66,65 +70,70 @@ Fail=0
 
 # The script tests both Xerox and Hfst transducers if available:
 for f in $fsttype; do
-	if [ $f == "xfst" ]; then
-		lookuptool="@LOOKUP@ -q -flags mbTT"
-		suffix="xfst"
-	elif [ $f == "hfst" ]; then
-		lookuptool="@HFST_LOOKUP@ -q"
-		suffix="hfstol"
-	else
-	    Fail=1
-		printf "ERROR: Unknown fst type! "
-	    echo "$f - FAIL"
-	    continue
-	fi
-	echo "$generator_file.$suffix"
-	if [ -f "$generator_file.$suffix" ]; then
-		let "transducer_found += 1"
+    if [ $f == "xfst" ]; then
+        lookup_tool="@LOOKUP@ -q -flags mbTT"
+        suffix="xfst"
+    elif [ $f == "hfst" ]; then
+        lookup_tool="@HFST_OPTIMIZED_LOOKUP@ -q"
+        suffix="hfstol"
+    else
+        Fail=1
+        printf "ERROR: Unknown fst type! "
+        echo "$f - FAIL"
+        continue
+    fi
+    if [ -f "$generator_file.$suffix" ]; then
+        let "transducer_found += 1"
 
 ###### Test non-comopunds: #######
-		# generate nouns in Singular, extract the resulting generated lemma,
-		# store it:
-        # Generer lemmaer i nouns med +N+Sg+Nom, lagre i generated-nouns
-        sed 's/$/+N+Sg+Nom/' $lemmas | $lookuptool $generator_file.$suffix \
-            | fgrep -v "+?" | grep -v "^$" | cut -f2 \
-            | sort -u > $generated_lemmas.$f.txt
+        # generate nouns in Singular, extract the resulting generated lemma,
+        # store it:
+        sed 's/$/+N+Sg+Nom/' $lemmas | $lookup_tool $generator_file.$suffix \
+            | cut -f2 | fgrep -v "+N+Sg" | grep -v "^$" | sort -u \
+            > $generated_lemmas.$f.txt 
 
-        # Generer plurale lemmaer i filtered-nouns med +N+Pl+Nom (som ikke
-        # lar seg generer med +N+Sg+Nom).
-        # Lagre dem i generated-nouns
-        sed 's/$/+N+Sg+Nom/' $lemmas \
-            | $lookuptool $generator_file.$suffix \
-            | fgrep "+?" | cut -d "+" -f1 | sed 's/$/+N+Pl+Nom/' \
-            | $lookuptool $generator_file.$suffix \
-            | cut -f2 | grep -v "^$" | sort -u >> $generated_lemmas.$f.txt 
+        # Generate nouns, extract those that do not generate in singular,
+        # generate the rest in plural:
+        sed 's/$/+N+Sg+Nom/' $lemmas | $lookup_tool $generator_file.$suffix \
+            | cut -f2 | grep "N+" | cut -d "+" -f1 | sed 's/$/+N+Pl+Nom/' \
+            | $lookup_tool $generator_file.$suffix | cut -f2 \
+            | grep -v "^$" >> $generated_lemmas.$f.txt 
 
-###### Collect results: #######
-		# Sort and compare original input with resulting output - the diff is
-		# stored and opened in SEE:
+###### Collect results, and generate debug info if FAIL: #######
+        # Sort and compare original input with resulting output - the diff is
+        # used to generate lemmas which are opened in SEE:
+        sort -u -o $generated_lemmas.$f.txt $generated_lemmas.$f.txt 
+        comm -23 $lemmas $generated_lemmas.$f.txt > $result_file.$f.txt
 
-# Sorter, unifiser
-sort -u -o $lemmas $lemmas 
-sort -u -o $generated_lemmas.$f.txt $generated_lemmas.$f.txt 
-
-# Sammenlikne: Former som er i lemmalista med ikke i lista med genererte former,
-# lagre i missingnounLemmas.txt. Formene generes med  +N+Sg+Nom for enklere debugging.
-comm -23 $lemmas $generated_lemmas.$f.txt \
-  | grep -v '^$' | sed 's/$/+N+Sg+Nom/' \
-  | $lookuptool $generator_file.$suffix > $result_file.$f.txt
-
-		# Open the diff file in SubEthaEdit (if there is a diff):
-		if [ -s $result_file.$f.txt ]; then
-			# Only open the failed lemmas in see if @SEE@ is defined:
-			if [ "$EXTEDITOR" ]; then
-				$EXTEDITOR $result_file.$f.txt
-			fi
-		    Fail=1
-		    echo "$f - FAIL"
-		    continue
-		fi
-	    echo "$f - PASS"
-	fi
+        # Open the diff file in SubEthaEdit (if there is a diff):
+        if [ -s $result_file.$f.txt ]; then
+            grep -v '^$' $result_file.$f.txt \
+              | sed 's/$/+N+Sg+Nom/' \
+              | $lookup_tool $generator_file.$suffix \
+              > $gen_result_file.$f.txt
+            # If we have an analyser, analyse the missing lemmas as well:
+            if test -e $analyser_file.$suffix ; then
+                grep -v '^$' $result_file.$f.txt \
+                  | $lookup_tool $analyser_file.$suffix \
+                  > $ana_result_file.$f.txt
+            fi
+            # Only open the failed lemmas in see if @SEE@ is defined:
+            if [ "$EXTEDITOR" ]; then
+                $EXTEDITOR $result_file.$f.txt
+                $EXTEDITOR $gen_result_file.$f.txt
+                $EXTEDITOR $ana_result_file.$f.txt
+            else
+                echo "There where problem lemmas. Details in:"
+                echo "* $result_file.$f.txt    "
+                echo "* $gen_result_file.$f.txt"
+                echo "* $ana_result_file.$f.txt"
+            fi
+            Fail=1
+            echo "$f - FAIL"
+            continue
+        fi
+        echo "$f - PASS"
+    fi
 done
 
 # When done, remove the generated data file:
@@ -132,7 +141,7 @@ rm -f $lemmas
 
 # At least one of the Xerox or HFST tests failed:
 if [ "$Fail" = "1" ]; then
-	exit 1
+    exit 1
 fi
 
 if [ $transducer_found -eq 0 ]; then
