The SMJ lemma generation test for proper nouns now updated with Lene’s and Ciprian’s improvements. Failing lemmas are now generated in the final output file, for easier debugging. It also uses the lemma extraction script in $GTCORE.
git-svn-id: https://gtsvn.uit.no/langtech/trunk/langs/smj@108997 c7155fb1-f0a7-4240-a2fc-2600b6f42f90

diff --git a/test/src/morphology/generate-propernoun-lemmas.sh.in b/test/src/morphology/generate-propernoun-lemmas.sh.in
--- a/test/src/morphology/generate-propernoun-lemmas.sh.in
+++ b/test/src/morphology/generate-propernoun-lemmas.sh.in
@@ -1,18 +1,38 @@
 #!/bin/bash
+# @configure_input@
+
+# Automake interprets the exit status as follows:
+# - an exit status of 0 will denote a success
+# - an exit status of 77 a skipped test
+# - an exit status of 99 a hard error
+# - any other exit status will denote a failure.
+
+# To run this test script only, do:
+#
+# make check TESTS=generate-noun-lemmas.sh
 
 # Dette skriptet tester at alle lemmaene i
 # $GTHOME/langs/smj/src/morphology/stems/propernouns.lexc kan genereres.
-# De som ikke kan genereres, kopieres til missingProperLemmas.txt
+# De som ikke kan genereres, kopieres til missingProperLemmas.*fst.txt
 
 ###### Variables: #######
-sourcefile=./../../../src/morphology/generated_files/smi-smj-propernouns.lexc
-generatorfile=./../../../src/generator-gt-norm
-resultfile=missingProperLemmas
+### in ###
+source_file=./../../../src/morphology/generated_files/smi-smj-propernouns.lexc
+generator_file=./../../../src/generator-gt-norm
+
+### out ###
+lemmas=./filtered-propnouns
+lemmas_attr=./filtered-attr-propnouns
+generated_lemmas=./generated-propnouns
+generated_attr_lemmas=./generated-attr-propnouns
+result_file=missing_proper_lemmas
 
 # Check that the source file exists:
-if [ ! -f "$sourcefile" ]; then
-	echo Source file not found: $sourcefile
-	exit 1
+if [ ! -f "$source_file" ]; then
+    echo
+    echo "*** Warning: Source file $source_file not found."
+    echo
+    exit 77
 fi
 
 # Use autotools mechanisms to only run the configured fst types in the tests:
@@ -31,17 +51,18 @@ fi
 EXTEDITOR=@SEE@
 
 ###### Extraction: #######
-grep ";" $sourcefile | grep -v "^\!" | egrep -v '(LAANTE|Attr)' \
-	| sed 's/% /€/g' |  tr ":+" " " | cut -d " " -f1 \
-	| tr -d "#" | tr "€" " " > props.tmp.txt
-grep ";" $sourcefile | grep -v "^\!" | grep LAANTE | sed 's/% /€/g' \
-	|  tr ":+" " " | cut -d " " -f1 | tr -d "#" \
-	| tr "€" " " | sed 's/$/laante/' >> props.tmp.txt
-sort -u props.tmp.txt > props.txt
-rm -f props.tmp.txt
-grep ";" $sourcefile | grep -v "^\!" | grep Attr | sed 's/% /€/g' \
-	|  tr ":+\t" " " | cut -d " " -f1 | tr -d "#" \
-	| tr "€" " " |  sort -u > attrprops.txt
+@GTCORE@/scripts/extract-lemmas.sh \
+	--exclude "(LAANTE|Attr)" $source_file \
+	> $lemmas.tmp
+@GTCORE@/scripts/extract-lemmas.sh \
+	--include "(LAANTE)" $source_file | sed 's/$/laante/' \
+	>> $lemmas.tmp
+sort -u $lemmas.tmp > $lemmas
+rm -f $lemmas.tmp
+
+@GTCORE@/scripts/extract-lemmas.sh \
+	--include "(Attr)" $source_file \
+	> $lemmas_attr
 
 ###### Start testing: #######
 transducer_found=0
@@ -60,40 +81,58 @@ for f in $fsttype; do
 	    echo "$f - FAIL"
 	    continue
 	fi
-	if [ -f "$generatorfile.$suffix" ]; then
+	if [ -f "$generator_file.$suffix" ]; then
 		let "transducer_found += 1"
 
-		sed 's/$/+N+Prop+Sg+Nom/'   props.txt \
-			| $lookuptool $generatorfile.$suffix | cut -f2 \
-			| grep -v "N+" | grep -v "^$" | sort -u > analprops.$f.txt
-		sed 's/$/+N+Prop+Sg+Nom/'   props.txt \
-			| $lookuptool $generatorfile.$suffix | cut -f2 \
+###### Test regular propers: #######
+		sed 's/$/+N+Prop+Sg+Nom/'   $lemmas \
+			| $lookuptool $generator_file.$suffix | cut -f2 \
+			| grep -v "N+" | grep -v "^$" | sort -u > $generated_lemmas.$f.txt
+
+###### Test plural propers: #######
+		sed 's/$/+N+Prop+Sg+Nom/'   $lemmas \
+			| $lookuptool $generator_file.$suffix | cut -f2 \
 			| grep "N+" | cut -d "+" -f1 | sed 's/$/+N+Prop+Pl+Nom/' \
-			| $lookuptool $generatorfile.$suffix | cut -f2 \
-			| grep -v "^$" | cut -d "+" -f1 >> analprops.$f.txt
-		sed 's/$/+N+Prop+Sg+Nom/'   props.txt \
-			| $lookuptool $generatorfile.$suffix | cut -f2 \
+			| $lookuptool $generator_file.$suffix | cut -f2 \
+			| grep -v "^$" | cut -d "+" -f1 >> $generated_lemmas.$f.txt
+
+###### Test plural propers: #######
+		sed 's/$/+N+Prop+Sg+Nom/'   $lemmas \
+			| $lookuptool $generator_file.$suffix | cut -f2 \
 			| grep "N+" | cut -d "+" -f1 | sed 's/$/+N+Prop+Pl+Nom/' \
-			| $lookuptool $generatorfile.$suffix | cut -f2 \
-			| grep "N+" | cut -d "+" -f1 > $resultfile.$f.txt
-		sed 's/$/+N+Prop+Attr/' attrprops.txt \
-			| $lookuptool $generatorfile.$suffix | cut -f2 \
-			| grep "N+" >> $resultfile.$f.txt
-		sed 's/$/+N+Prop+Attr/' attrprops.txt \
-			| $lookuptool $generatorfile.$suffix | cut -f2 \
-			|  grep -v "N+" | grep -v "^$" | sort -u > analattrprops.$f.txt
-		sort -u -o analprops.$f.txt analprops.$f.txt
-		comm -23 props.txt analprops.$f.txt > $resultfile.$f.txt
-		comm -23 attrprops.txt analattrprops.$f.txt >> $resultfile.$f.txt
-		sort -u -o $resultfile.$f.txt $resultfile.$f.txt
+			| $lookuptool $generator_file.$suffix | cut -f2 \
+			| grep "N+" | cut -d "+" -f1 > $result_file.$f.txt
+
+###### Test attr propers: #######
+		sed 's/$/+N+Prop+Attr/' $lemmas_attr \
+			| $lookuptool $generator_file.$suffix | cut -f2 \
+			| grep "N+" >> $result_file.$f.txt
+
+###### Test attr propers: #######
+		sed 's/$/+N+Prop+Attr/' $lemmas_attr \
+			| $lookuptool $generator_file.$suffix | cut -f2 \
+			|  grep -v "N+" | grep -v "^$" \
+			| sort -u > $generated_attr_lemmas.$f.txt
+
+###### Collect results: #######
+		sort -u -o $generated_lemmas.$f.txt $generated_lemmas.$f.txt
+		comm -23 $lemmas $generated_lemmas.$f.txt > $result_file.$f.txt
+		comm -23 $lemmas_attr $generated_attr_lemmas.$f.txt >> $result_file.$f.txt
+		sort -u -o $result_file.$f.txt $result_file.$f.txt
+
+# Sammenlikne: Former som er i lemmalista men ikke i lista med genererte former,
+# lagre i $result_file.$f.txt. Formene generes med  +N+Prop+Sg+Nom for
+# enklere debugging.
+		comm -23 $lemmas $generated_lemmas.$f.txt | sed 's/$/+N+Prop+Sg+Nom/' \
+		     | $lookuptool $generator_file.$suffix >> $result_file.$f.txt
 
 		# if at least one word is found, the test failed, and the list of failed
 		# lemmas is opened in SubEthaEdit:
-		if [ -s $resultfile.$f.txt ]
+		if [ -s $result_file.$f.txt ]
 		then
 			# Only open the failed lemmas in see if @SEE@ is defined:
 			if [ "$EXTEDITOR" ]; then
-				$EXTEDITOR $resultfile.$f.txt
+				$EXTEDITOR $result_file.$f.txt
 			fi
 		    Fail=1
 		    echo "$f - FAIL"
@@ -104,7 +143,7 @@ for f in $fsttype; do
 done
 
 # Delete temporary files:
-rm -f *props.txt
+rm -f $lemmas $lemmas_attr $generated_lemmas $generated_attr_lemmas
 
 # At least one of the Xerox or HFST tests failed:
 if [ "$Fail" = "1" ]; then
