The test scripts updated to what Trond copied from SME during the weekend, with one small change by Sandra. The code is Ciprian's, Lene's and Trond's improvements of the original lemma generation test scripts (and some regressions or questionable decisions that I will return to soon).
git-svn-id: https://gtsvn.uit.no/langtech/trunk/langs/smj@108589 c7155fb1-f0a7-4240-a2fc-2600b6f42f90

diff --git a/test/src/morphology/generate-verb-lemmas.sh.in b/test/src/morphology/generate-verb-lemmas.sh.in
--- a/test/src/morphology/generate-verb-lemmas.sh.in
+++ b/test/src/morphology/generate-verb-lemmas.sh.in
@@ -1,17 +1,41 @@
 #!/bin/bash
+# @configure_input@
 
-# Dette skriptet tester at alle lemmaene i verb-sma-lex.txt kan genereres. De
-# som ikke kan genereres, kopieres til missingVerbLemmas.txt
+# Automake interprets the exit status as follows:
+# - an exit status of 0 will denote a success
+# - an exit status of 77 a skipped test
+# - an exit status of 99 a hard error
+# - any other exit status will denote a failure.
+
+# To run this test script only, do:
+#
+# make check TESTS=generate-verb-lemmas.sh
+
+# This test script will test that all verb lemmas do generate as themselves.
+# Extend as needed, and copy to new files to adapt to other parts of speech.
+# The changes usually needed are:
+#
+# 1. change the reference to the source file (line 23)
+# 2. extend the extract lemmas egrep expression (lines 53 ff)
+# 3. adapt the tag addition and lemma generation instructions (lines 79 ff)
 
 ###### Variables: #######
-sourcefile=${srcdir}/../../../src/morphology/stems/verbs.lexc
-generatorfile=./../../../src/generator-gt-norm
-resultfile=missingVerbLemmas
+### in ###
+source_file=${srcdir}/../../../src/morphology/stems/verbs.lexc
+generator_file=./../../../src/generator-gt-norm
 
-# Check that the source file exists:
-if [ ! -f "$sourcefile" ]; then
-	echo Source file not found: $sourcefile
-	exit 1
+### out ###
+lemmas=./filtered-verbs
+generated_lemmas=./generated-verbs
+result_file=${srcdir}/../../data/missing_verb_lemmas
+
+
+# FAIL if source file does not exist:
+if [ ! -f $source_file ]; then
+    echo
+    echo "*** Warning: Source file $source_file not found."
+    echo
+    exit 77
 fi
 
 # Use autotools mechanisms to only run the configured fst types in the tests:
@@ -20,7 +44,7 @@ fsttype=
 @CAN_XFST_TRUE@fsttype="$fsttype xfst"
 
 # Exit if both hfst and xerox have been shut off:
-if [ -z $fsttype ]; then
+if test -z "$fsttype" ; then
     echo "All transducer types have been shut off at configure time."
     echo "Nothing to test. Skipping."
     exit 77
@@ -29,15 +53,22 @@ fi
 # Get external Mac editor for viewing failed results from configure:
 EXTEDITOR=@SEE@
 
-###### Extraction: #######
-grep ";" $sourcefile | grep -v "^\!" \
-	| egrep -v "(STRAYFORMS|ENDLEX|\+V)" | tr ":+\t" " " | cut -d " " -f1 \
-	| tr -d "#" | sort -u > verbs.txt
+##### Extract lemmas #####
+### don't use extract-lemmas.sh ###
+# Hent ut lemmaer, bortsett fra utkommmenterte (^\!),  dem med hardkoding
+# for spesielle former (STRAYFORMS|ENDLEX), eller negasjonsverbet (+Neg, som
+# ikke har infinitivform), LexSub (som blir filtrert bort fra normgenerator).
+# Lemmaene lagres som $lemmas.
+
+grep ";" $source_file | \
+  grep -v "^\!" | egrep -v '(STRAYFORMS|ENDLEX|\+Err\/|\+Neg)' | \
+  tr ":+" " " | cut -d " " -f1 | tr -d "%" | sort -u > $lemmas
 
 ###### Start testing: #######
 transducer_found=0
 Fail=0
 
+# The script tests both Xerox and Hfst transducers if available:
 for f in $fsttype; do
 	if [ $f == "xfst" ]; then
 		lookuptool="@LOOKUP@ -q -flags mbTT"
@@ -47,38 +78,39 @@ for f in $fsttype; do
 		suffix="hfstol"
 	else
 	    Fail=1
-		echo "Unknown fst type!"
+		printf "ERROR: Unknown fst type! "
 	    echo "$f - FAIL"
 	    continue
 	fi
-	if [ -f "$generatorfile.$suffix" ]; then
+	if [ -f "$generator_file.$suffix" ]; then
 		let "transducer_found += 1"
 
-#### First we try to generate the infinitives:
-		sed 's/$/+V+Inf/' verbs.txt \
-			| $lookuptool $generatorfile.$suffix \
-			| cut -f2 | grep -v "V+" | grep -v "^$" | sort -u > analverbs.$f.txt
+###### Test generation: #######
+		# generate verbs, extract the resulting generated lemma,
+		# store it:
 
-#### Kvifor trekkjer vi ut +N-analyser, og genererer substantiv i ein verb-test?
-		cat verbs.txt | sed 's/$/+V+Inf/' \
-			| $lookuptool $generatorfile.$suffix \
-			| cut -f2 | grep "N+" | cut -d "+" -f1 | sed 's/$/+N+Pl+Nom/' \
-			| $lookuptool $generatorfile.$suffix | cut -f2 \
-			| grep -v "^$" >> analverbs.$f.txt
+# Generer infitivsformen av verblemmaene, fjern dem som ikke gir analyse (de har V+ i output),
+# lagres som fil som har blitt deklarert oppe.
+		sed 's/$/+V+Inf/' $lemmas | $lookuptool $generator_file.$suffix \
+            | cut -f2 | grep -v "V+" | grep -v "^$" | sort -u > $generated_lemmas.$f.txt 
 
-#### Sort & uniq resultatet
-		sort -u -o analverbs.$f.txt analverbs.$f.txt
+###### Collect results: #######
+		# Sort and compare original input with resulting output - the diff is
+		# stored and opened in SEE:
+		
+# Sammenlikne lista med verblemmaer med den genererte lista med infinitivsformer.
+# Formene som er i verblemmalista, men ikke i den genererte lista, kopieres til
+# missingverbLemmas.txt. Formene generes med  +V+Inf for lettere debugging.
 
-#### Samanlikne inndata med utdata:
-		comm -23 verbs.txt analverbs.$f.txt > $resultfile.$f.txt
+		comm -23 $lemmas $generated_lemmas.$f.txt \
+		     | grep -v '^$' | sed 's/$/+V+Inf/' \
+		     | $lookuptool $generator_file.$suffix > $result_file.$f.txt
 
-		# if at least one word is found, the test failed, and the list of failed
-		# lemmas is opened in SubEthaEdit:
-		if [ -s $resultfile.$f.txt ]
-		then
+		# Open the diff file in SubEthaEdit (if there is a diff):
+		if [ -s $result_file.$f.txt ]; then
 			# Only open the failed lemmas in see if @SEE@ is defined:
 			if [ "$EXTEDITOR" ]; then
-				$EXTEDITOR $resultfile.$f.txt
+				$EXTEDITOR $result_file.$f.txt
 			fi
 		    Fail=1
 		    echo "$f - FAIL"
@@ -88,8 +120,8 @@ for f in $fsttype; do
 	fi
 done
 
-# Delete temporary files:
-rm *verbs.*.txt
+# When done, remove the generated data file:
+rm -f $lemmas $generated_lemmas.$f.txt
 
 # At least one of the Xerox or HFST tests failed:
 if [ "$Fail" = "1" ]; then
@@ -97,6 +129,6 @@ if [ "$Fail" = "1" ]; then
 fi
 
 if [ $transducer_found -eq 0 ]; then
-    echo No transducer found
-    exit 1
+    echo ERROR: No transducer found
+    exit 77
 fi
