Multiple changes to make sure only the tests for the transducer types that have been turned on in the configuration are run. Ie, if hfst is off, don't run the hfst transducer tests.
git-svn-id: https://gtsvn.uit.no/langtech/trunk/langs/smj@66231 c7155fb1-f0a7-4240-a2fc-2600b6f42f90

diff --git a/test/src/morphology/test-noun-generation.sh.in b/test/src/morphology/test-noun-generation.sh.in
--- a/test/src/morphology/test-noun-generation.sh.in
+++ b/test/src/morphology/test-noun-generation.sh.in
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-# Dette skriptet tester at nesten alle lemmaene i noun-sma-lex.txt kan genereres.
+# Dette skriptet tester at alle lemmaene i noun-sma-lex.txt kan genereres.
 # De som ikke kan genereres, kopieres til missingNounLemmas.txt
 
 ###### Variables: #######
@@ -14,6 +14,18 @@ if [ ! -f "$sourcefile" ]; then
 	exit 1
 fi
 
+# Use autotools mechanisms to only run the configured fst types in the tests:
+fsttype=
+@CAN_HFST_TRUE@fsttype="$fsttype hfst"
+@CAN_XFST_TRUE@fsttype="$fsttype xfst"
+
+# Exit if both hfst and xerox have been shut off:
+if [ -z $fsttype ]; then
+    echo "All transducer types have been shut off at configure time."
+    echo "Nothing to test. Skipping."
+    exit 77
+fi
+
 ###### Extraction: #######
 # extract non-compounding lemmas:
 grep ";" $sourcefile | grep -v "^\!" \
@@ -21,6 +33,7 @@ grep ";" $sourcefile | grep -v "^\!" \
 	| sed 's/%:/¢/g' | tr ":+\t" " " | cut -d " " -f1 | tr -d "#" \
 	| tr "€" " " | tr "¢" ":" \
 	| sort -u | grep -v '^$' > nouns.txt
+
 # extract compounding lemmas:
 grep ";" $sourcefile | grep -v "^\!" \
 	| grep ' R '| tr ":+\t" " " | cut -d " " -f1 | tr -d "#" \
@@ -34,62 +47,65 @@ grep ";" $sourcefile | grep -v "^\!" \
 transducer_found=0
 Fail=0
 
-for f in  .xfst .hfst; do
-	if [ $f == ".xfst" ]; then
+for f in $fsttype; do
+	if [ $f == "xfst" ]; then
 		lookuptool="@LOOKUP@ -q -flags mbTT"
-		fsttype=xfst
-	else
+	elif [ $f == "hfst" ]; then
 		lookuptool="@HFST_LOOKUP@ -q"
-		fsttype=hfst
+	else
+	    Fail=1
+		echo "Unknown fst type!"
+	    echo "$f - FAIL"
+	    continue
 	fi
-	if [ -f "$generatorfile$f" ]; then
+	if [ -f "$generatorfile.$f" ]; then
 		let "transducer_found += 1"
 
 ###### Test non-comopunds: #######
 		# generate nouns in Singular, extract the resulting generated lemma,
 		# store it:
-		sed 's/$/+N+Sg+Nom/' nouns.txt | $lookuptool $generatorfile$f \
-			| cut -f2 | grep -v "N+" | grep -v "^$" | sort -u > analnouns$f.txt 
+		sed 's/$/+N+Sg+Nom/' nouns.txt | $lookuptool $generatorfile.$f \
+			| cut -f2 | grep -v "N+" | grep -v "^$" | sort -u > analnouns.$f.txt 
 		# Generate nouns, extract those that do not generate in singular,
 		# generate the rest in plural:
-		sed 's/$/+N+Sg+Nom/' nouns.txt | $lookuptool $generatorfile$f \
+		sed 's/$/+N+Sg+Nom/' nouns.txt | $lookuptool $generatorfile.$f \
 			| cut -f2 | grep "N+" | cut -d "+" -f1 | sed 's/$/+N+Pl+Nom/' \
-			| $lookuptool $generatorfile$f | cut -f2 \
-			| grep -v "^$" >> analnouns$f.txt 
+			| $lookuptool $generatorfile.$f | cut -f2 \
+			| grep -v "^$" >> analnouns.$f.txt 
 
 ###### Test comopunds: #######
 		# Test nouns that only can generate as compounds:
 		sed 's/$/+N+Cmp#bijlla+N+Sg+Nom/' Rnouns.txt \
-			| $lookuptool $generatorfile$f | cut -f2 | sed 's/bijlla$//' \
-			| grep -v '^$' >> Ranalnouns$f.txt
+			| $lookuptool $generatorfile.$f | cut -f2 | sed 's/bijlla$//' \
+			| grep -v '^$' >> Ranalnouns.$f.txt
 		sed 's/$/+N+Cmp-#bijlla+N+Sg+Nom/' RHnouns.txt \
-			| $lookuptool $generatorfile$f | cut -f2 | sed 's/\-bijlla$//' \
-			| grep -v '^$' >> RHanalnouns$f.txt
+			| $lookuptool $generatorfile.$f | cut -f2 | sed 's/\-bijlla$//' \
+			| grep -v '^$' >> RHanalnouns.$f.txt
 
 ###### Collect results: #######
 		# Sort and compare original input with resulting output - the diff is
 		# stored and opened in SEE:
-		sort -u -o analnouns$f.txt analnouns$f.txt 
-		sort -u -o Ranalnouns$f.txt Ranalnouns$f.txt 
-		sort -u -o RHanalnouns$f.txt RHanalnouns$f.txt 
-		comm -23 nouns.txt analnouns$f.txt > $resultfile$f.txt
-		comm -23 Rnouns.txt Ranalnouns$f.txt >> $resultfile$f.txt
-		comm -23 RHnouns.txt RHanalnouns$f.txt >> $resultfile$f.txt
+		sort -u -o analnouns.$f.txt analnouns.$f.txt 
+		sort -u -o Ranalnouns.$f.txt Ranalnouns.$f.txt 
+		sort -u -o RHanalnouns.$f.txt RHanalnouns.$f.txt 
+		comm -23 nouns.txt analnouns.$f.txt > $resultfile.$f.txt
+		comm -23 Rnouns.txt Ranalnouns.$f.txt >> $resultfile.$f.txt
+		comm -23 RHnouns.txt RHanalnouns.$f.txt >> $resultfile.$f.txt
 
 		# if at least one word is found, the test failed, and the list of failed
 		# lemmas is opened in SubEthaEdit:
-		if [ `wc -w $resultfile$f.txt | tr -s ' ' | cut -d' ' -f2` -gt 0 ]; then
-			see $resultfile$f.txt
+		if [ `wc -w $resultfile.$f.txt | tr -s ' ' | cut -d' ' -f2` -gt 0 ]; then
+			see $resultfile.$f.txt
 		    Fail=1
-		    echo "$fsttype - FAIL"
+		    echo "$f - FAIL"
 		    continue
 		fi
-	    echo "$fsttype - PASS"
+	    echo "$f - PASS"
 	fi
 done
 
 # Delete temporary files:
-rm -f *nouns.txt
+rm -f *nouns.*.txt
 
 # At least one of the Xerox or HFST tests failed:
 if [ "$Fail" = "1" ]; then
